# what worlds to disable lava generators
disabled-worlds:
  - "world_nether"

main-menu:
  blocks: "&a\u27A5 &2[BLOCK]: &7[PERCENT]%"
  generator:
    name: "&a&l[NAME] &7(Level [LEVEL])"
    lore:
      - "&7&o(Click to modify items)"
      - ""
      - "&2&lLevels"
      - "&a\u27A5 &7Max Levels: &n[MAX]"
      - ""
      - "&2&lPermission:"
      - "&7oregenerator.use.[NAME]"

select-menu:
  item-name: "&a&l[NAME] &7(Level [LEVEL])"
  item-line: "&a[BLOCK] &f\u00bb &7([PERCENT]%)"
  status:
    locked: "&7[&6&lCLICK TO &nUNLOCKED&7]"
    disabled: "&aStatus &f\u00bb &7[&c&lDISABLED&7]"
    selected: "&aStatus &f\u00bb &7[&a&lSELECTED&7]"
  item-lore:
    - "&7(click to select this)"
    - ""
    - "&2&lPERCENTAGES"
    - "[ITEMS]"
    - ""
    - "[STATUS]"

level-cost:
  default:
    2: 10000
  vip:
    2: 20000
    3: 30000

gui-menus:
  titles:
    main-menu: "&8Generator Menu"
    edit-menu: "&8Edit Blocks Menu"
    modify-menu: "&8Modify Menu"
  buttons:
    exit-name: "&4Exit"
    edit-name: "&aEdit Blocks"

generator-item:
  default:
    name: "&a&lDEFAULT &7&lGENERATOR"
    lore:
      - "&7Place me to create a custom generator at"
      - "&7Any location."